# Generated by Django 4.0.1 on 2022-09-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_on_Sale',
            field=models.BooleanField(default=False),
        ),
    ]
