# Generated by Django 4.0.1 on 2022-09-13 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_product_is_on_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='partenaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_partenaire', to='shop.category'),
        ),
    ]
