# Generated by Django 4.0.1 on 2022-09-13 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_partenaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='partenaire',
        ),
    ]
